version: '3'

services:
  app:
    build: .
    volumes:
      - .:/var/www
    ports:
      - "80:8000"  # Mapeia a porta 80 do host para a porta 8000 do contêiner
    command: php artisan serve --host=0.0.0.0 --port=8000  # Executa o servidor Laravel
    networks:
      - laravel-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata:
